version: 0.2
phases:
  install:
    commands:
      - echo "Installing Apache HTTP Server (httpd)"
      - sudo yum update -y
      - sudo yum install httpd -y
  build:
    commands:
      - echo "Build started on $(date)"
      - sudo cp index.html /var/www/html/
  post_build:
    commands:
      - echo "Configuring Apache httpd"
artifacts:
  files:
    - "**/*"
